### ISSUE TITLE
When editor is editable with big code the edition turn slow

### ISSUE THREAD

**Issue by maxneo4** [koca/vue-prism-editor#9]
Hi, Great job with that editor. I'm using with liquid templates and json data.
I'm working in inline template liquid render, but with **big json content** edit in line is very slow.

You can see it in
[https://codesandbox.io/s/00rxvx91yv](https://codesandbox.io/s/00rxvx91yv)
or
[https://00rxvx91yv.codesandbox.io/](https://00rxvx91yv.codesandbox.io/)

test delete some few chars or write some news

I think an option to update every n keydowns... or update in demand with an action.. I let you consider best.

Thank you.

**Comment by koca** [comment]
Hi, thanks! glad you liked it :)

As I mention in the README. This editor is not intended to use with big chunks of input. At least with the current implementation.

Few things came to my mind:

- Use/make something like react-prism-renderer, so we won't have to re-render everything when the code is changed. But I'm thinking that won't solve the issue either because your input generates huge output. Rendering that much output should take time ^^.

- use web workers? but I'm not sure if the slow part is when prism highlights or when Vue renders the output.

I guess rendering only the parts which are in the viewport would help 🤔

**Comment by koca** [comment]
Update:
Tried debouncing, it works better.

**Comment by maxneo4** [comment]
You are right, in this moment the editor is good for normal size contents, the big contents is a goal in the future, ideal if you get render only the parts wich are in edition. I'm following you in your advance.  :)

**Comment by koca** [comment]
Hi, I just published the new version so you should be able to debounce:

> use new version `vue-prism-editor@0.1.2`

```js
// import debounce from lodash
import debounce from "lodash/debounce"

// your current `changeJson` method
methods:{
	changeJson: function(plain) {
		this.currentJsondata = plain;
    }
}
// change it like below:
methods:{
	changeJson: debounce(function(plain){
		this.currentJsondata = plain;
	}, 2000)
}
```

It's not going to make a huge difference but should be noticeable ^^.
Good luck :)
